POST http://localhost:3000/test/order
Content-Type: application/json

{
    "kode_pemesanan": "ORD123",
    "tanggal_pemesanan": "2023-05-27T10:00:00Z",
    "tiketId": 1,
    "userId": 1,
    "status": "PAID"
}
